version: '3.9'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_PASSWORD: root
    networks:
      - nginx-node

  node:
    container_name: node
    build:
      context: ./node
    volumes:
      - ./node:/app
    networks:
      - nginx-node
    tty: true
    depends_on:
      - mysql
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - node
      - mysql
    networks:
      - nginx-node

networks:
  nginx-node:
    driver: bridge
